//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmIntegration.Core.ServiceReferenceNaumen {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://naumen.ru/soap/server", ConfigurationName="ServiceReferenceNaumen.Service")]
    public interface Service {
        
        // CODEGEN: Контракт генерации сообщений с операцией EditExcl не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void EditExcl(CrmIntegration.Core.ServiceReferenceNaumen.EditExclRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task EditExclAsync(CrmIntegration.Core.ServiceReferenceNaumen.EditExclRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией AddFile не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void AddFile(CrmIntegration.Core.ServiceReferenceNaumen.AddFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task AddFileAsync(CrmIntegration.Core.ServiceReferenceNaumen.AddFileRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией Find не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void Find(CrmIntegration.Core.ServiceReferenceNaumen.FindRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task FindAsync(CrmIntegration.Core.ServiceReferenceNaumen.FindRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией Delete не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void Delete(CrmIntegration.Core.ServiceReferenceNaumen.DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task DeleteAsync(CrmIntegration.Core.ServiceReferenceNaumen.DeleteRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией CreateExcl не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void CreateExcl(CrmIntegration.Core.ServiceReferenceNaumen.CreateExclRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task CreateExclAsync(CrmIntegration.Core.ServiceReferenceNaumen.CreateExclRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией Edit не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void Edit(CrmIntegration.Core.ServiceReferenceNaumen.EditRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task EditAsync(CrmIntegration.Core.ServiceReferenceNaumen.EditRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией GetFile не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void GetFile(CrmIntegration.Core.ServiceReferenceNaumen.GetFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task GetFileAsync(CrmIntegration.Core.ServiceReferenceNaumen.GetFileRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией Create не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void Create(CrmIntegration.Core.ServiceReferenceNaumen.CreateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task CreateAsync(CrmIntegration.Core.ServiceReferenceNaumen.CreateRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией Get не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(hasAttributesRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(entry[]))]
        void Get(CrmIntegration.Core.ServiceReferenceNaumen.GetRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        System.Threading.Tasks.Task GetAsync(CrmIntegration.Core.ServiceReferenceNaumen.GetRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class editExclRequest : hasAttributesRequest {
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(findRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createExclRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(createRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(editExclRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(editRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public abstract partial class hasAttributesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessKeyField;
        
        private entry[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accessKey {
            get {
                return this.accessKeyField;
            }
            set {
                this.accessKeyField = value;
                this.RaisePropertyChanged("accessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public entry[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class entry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private anyType valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public anyType value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class anyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("aggregate", typeof(aggregateValue), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("dateTimeInterval", typeof(dateTimeInterval), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("hyperlink", typeof(hyperlink), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("long", typeof(long), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("objects", typeof(objectsStr), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("period", typeof(period), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("string", typeof(string), Order=0)]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class aggregateValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ouField;
        
        private string teamField;
        
        private string employeeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ou {
            get {
                return this.ouField;
            }
            set {
                this.ouField = value;
                this.RaisePropertyChanged("ou");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string team {
            get {
                return this.teamField;
            }
            set {
                this.teamField = value;
                this.RaisePropertyChanged("team");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
                this.RaisePropertyChanged("employee");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class getRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessKeyField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accessKey {
            get {
                return this.accessKeyField;
            }
            set {
                this.accessKeyField = value;
                this.RaisePropertyChanged("accessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class getFileRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessKeyField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accessKey {
            get {
                return this.accessKeyField;
            }
            set {
                this.accessKeyField = value;
                this.RaisePropertyChanged("accessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class deleteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessKeyField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accessKey {
            get {
                return this.accessKeyField;
            }
            set {
                this.accessKeyField = value;
                this.RaisePropertyChanged("accessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class addFileRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accessKeyField;
        
        private string contentField;
        
        private string mimeTypeField;
        
        private string sourceUUIDField;
        
        private string titleField;
        
        private string attrCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string accessKey {
            get {
                return this.accessKeyField;
            }
            set {
                this.accessKeyField = value;
                this.RaisePropertyChanged("accessKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
                this.RaisePropertyChanged("mimeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sourceUUID {
            get {
                return this.sourceUUIDField;
            }
            set {
                this.sourceUUIDField = value;
                this.RaisePropertyChanged("sourceUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string attrCode {
            get {
                return this.attrCodeField;
            }
            set {
                this.attrCodeField = value;
                this.RaisePropertyChanged("attrCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class period : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string periodStartField;
        
        private string periodEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string periodStart {
            get {
                return this.periodStartField;
            }
            set {
                this.periodStartField = value;
                this.RaisePropertyChanged("periodStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string periodEnd {
            get {
                return this.periodEndField;
            }
            set {
                this.periodEndField = value;
                this.RaisePropertyChanged("periodEnd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class objectsStr : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] objectsStr1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objectsStr", Order=0)]
        public string[] objectsStr1 {
            get {
                return this.objectsStr1Field;
            }
            set {
                this.objectsStr1Field = value;
                this.RaisePropertyChanged("objectsStr1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class hyperlink : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class dateTimeInterval : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long lengthField;
        
        private bool lengthFieldSpecified;
        
        private string intervalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
                this.RaisePropertyChanged("lengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
                this.RaisePropertyChanged("interval");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class findRequest : hasAttributesRequest {
        
        private string fqnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fqn {
            get {
                return this.fqnField;
            }
            set {
                this.fqnField = value;
                this.RaisePropertyChanged("fqn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class createExclRequest : hasAttributesRequest {
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class createRequest : hasAttributesRequest {
        
        private string fqnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string fqn {
            get {
                return this.fqnField;
            }
            set {
                this.fqnField = value;
                this.RaisePropertyChanged("fqn");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://naumen.ru/soap/server")]
    public partial class editRequest : hasAttributesRequest {
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
                this.RaisePropertyChanged("uuid");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditExclRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.editExclRequest EditExclRequest;
        
        public EditExclRequest1() {
        }
        
        public EditExclRequest1(CrmIntegration.Core.ServiceReferenceNaumen.editExclRequest EditExclRequest) {
            this.EditExclRequest = EditExclRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddFileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.addFileRequest AddFileRequest;
        
        public AddFileRequest1() {
        }
        
        public AddFileRequest1(CrmIntegration.Core.ServiceReferenceNaumen.addFileRequest AddFileRequest) {
            this.AddFileRequest = AddFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.findRequest FindRequest;
        
        public FindRequest1() {
        }
        
        public FindRequest1(CrmIntegration.Core.ServiceReferenceNaumen.findRequest FindRequest) {
            this.FindRequest = FindRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.deleteRequest DeleteRequest;
        
        public DeleteRequest1() {
        }
        
        public DeleteRequest1(CrmIntegration.Core.ServiceReferenceNaumen.deleteRequest DeleteRequest) {
            this.DeleteRequest = DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateExclRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.createExclRequest CreateExclRequest;
        
        public CreateExclRequest1() {
        }
        
        public CreateExclRequest1(CrmIntegration.Core.ServiceReferenceNaumen.createExclRequest CreateExclRequest) {
            this.CreateExclRequest = CreateExclRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.editRequest EditRequest;
        
        public EditRequest1() {
        }
        
        public EditRequest1(CrmIntegration.Core.ServiceReferenceNaumen.editRequest EditRequest) {
            this.EditRequest = EditRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.getFileRequest GetFileRequest;
        
        public GetFileRequest1() {
        }
        
        public GetFileRequest1(CrmIntegration.Core.ServiceReferenceNaumen.getFileRequest GetFileRequest) {
            this.GetFileRequest = GetFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.createRequest CreateRequest;
        
        public CreateRequest1() {
        }
        
        public CreateRequest1(CrmIntegration.Core.ServiceReferenceNaumen.createRequest CreateRequest) {
            this.CreateRequest = CreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://naumen.ru/soap/server", Order=0)]
        public CrmIntegration.Core.ServiceReferenceNaumen.getRequest GetRequest;
        
        public GetRequest1() {
        }
        
        public GetRequest1(CrmIntegration.Core.ServiceReferenceNaumen.getRequest GetRequest) {
            this.GetRequest = GetRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceChannel : CrmIntegration.Core.ServiceReferenceNaumen.Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<CrmIntegration.Core.ServiceReferenceNaumen.Service>, CrmIntegration.Core.ServiceReferenceNaumen.Service {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.EditExcl(CrmIntegration.Core.ServiceReferenceNaumen.EditExclRequest1 request) {
            base.Channel.EditExcl(request);
        }
        
        public void EditExcl(CrmIntegration.Core.ServiceReferenceNaumen.editExclRequest EditExclRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.EditExclRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.EditExclRequest1();
            inValue.EditExclRequest = EditExclRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).EditExcl(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.EditExclAsync(CrmIntegration.Core.ServiceReferenceNaumen.EditExclRequest1 request) {
            return base.Channel.EditExclAsync(request);
        }
        
        public System.Threading.Tasks.Task EditExclAsync(CrmIntegration.Core.ServiceReferenceNaumen.editExclRequest EditExclRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.EditExclRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.EditExclRequest1();
            inValue.EditExclRequest = EditExclRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).EditExclAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.AddFile(CrmIntegration.Core.ServiceReferenceNaumen.AddFileRequest1 request) {
            base.Channel.AddFile(request);
        }
        
        public void AddFile(CrmIntegration.Core.ServiceReferenceNaumen.addFileRequest AddFileRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.AddFileRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.AddFileRequest1();
            inValue.AddFileRequest = AddFileRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).AddFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.AddFileAsync(CrmIntegration.Core.ServiceReferenceNaumen.AddFileRequest1 request) {
            return base.Channel.AddFileAsync(request);
        }
        
        public System.Threading.Tasks.Task AddFileAsync(CrmIntegration.Core.ServiceReferenceNaumen.addFileRequest AddFileRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.AddFileRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.AddFileRequest1();
            inValue.AddFileRequest = AddFileRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).AddFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.Find(CrmIntegration.Core.ServiceReferenceNaumen.FindRequest1 request) {
            base.Channel.Find(request);
        }
        
        public void Find(CrmIntegration.Core.ServiceReferenceNaumen.findRequest FindRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.FindRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.FindRequest1();
            inValue.FindRequest = FindRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).Find(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.FindAsync(CrmIntegration.Core.ServiceReferenceNaumen.FindRequest1 request) {
            return base.Channel.FindAsync(request);
        }
        
        public System.Threading.Tasks.Task FindAsync(CrmIntegration.Core.ServiceReferenceNaumen.findRequest FindRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.FindRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.FindRequest1();
            inValue.FindRequest = FindRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).FindAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.Delete(CrmIntegration.Core.ServiceReferenceNaumen.DeleteRequest1 request) {
            base.Channel.Delete(request);
        }
        
        public void Delete(CrmIntegration.Core.ServiceReferenceNaumen.deleteRequest DeleteRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.DeleteRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.DeleteRequest1();
            inValue.DeleteRequest = DeleteRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).Delete(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.DeleteAsync(CrmIntegration.Core.ServiceReferenceNaumen.DeleteRequest1 request) {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(CrmIntegration.Core.ServiceReferenceNaumen.deleteRequest DeleteRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.DeleteRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.DeleteRequest1();
            inValue.DeleteRequest = DeleteRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.CreateExcl(CrmIntegration.Core.ServiceReferenceNaumen.CreateExclRequest1 request) {
            base.Channel.CreateExcl(request);
        }
        
        public void CreateExcl(CrmIntegration.Core.ServiceReferenceNaumen.createExclRequest CreateExclRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.CreateExclRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.CreateExclRequest1();
            inValue.CreateExclRequest = CreateExclRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).CreateExcl(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.CreateExclAsync(CrmIntegration.Core.ServiceReferenceNaumen.CreateExclRequest1 request) {
            return base.Channel.CreateExclAsync(request);
        }
        
        public System.Threading.Tasks.Task CreateExclAsync(CrmIntegration.Core.ServiceReferenceNaumen.createExclRequest CreateExclRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.CreateExclRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.CreateExclRequest1();
            inValue.CreateExclRequest = CreateExclRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).CreateExclAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.Edit(CrmIntegration.Core.ServiceReferenceNaumen.EditRequest1 request) {
            base.Channel.Edit(request);
        }
        
        public void Edit(CrmIntegration.Core.ServiceReferenceNaumen.editRequest EditRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.EditRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.EditRequest1();
            inValue.EditRequest = EditRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).Edit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.EditAsync(CrmIntegration.Core.ServiceReferenceNaumen.EditRequest1 request) {
            return base.Channel.EditAsync(request);
        }
        
        public System.Threading.Tasks.Task EditAsync(CrmIntegration.Core.ServiceReferenceNaumen.editRequest EditRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.EditRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.EditRequest1();
            inValue.EditRequest = EditRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).EditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.GetFile(CrmIntegration.Core.ServiceReferenceNaumen.GetFileRequest1 request) {
            base.Channel.GetFile(request);
        }
        
        public void GetFile(CrmIntegration.Core.ServiceReferenceNaumen.getFileRequest GetFileRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.GetFileRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.GetFileRequest1();
            inValue.GetFileRequest = GetFileRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).GetFile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.GetFileAsync(CrmIntegration.Core.ServiceReferenceNaumen.GetFileRequest1 request) {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task GetFileAsync(CrmIntegration.Core.ServiceReferenceNaumen.getFileRequest GetFileRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.GetFileRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.GetFileRequest1();
            inValue.GetFileRequest = GetFileRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.Create(CrmIntegration.Core.ServiceReferenceNaumen.CreateRequest1 request) {
            base.Channel.Create(request);
        }
        
        public void Create(CrmIntegration.Core.ServiceReferenceNaumen.createRequest CreateRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.CreateRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.CreateRequest1();
            inValue.CreateRequest = CreateRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).Create(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.CreateAsync(CrmIntegration.Core.ServiceReferenceNaumen.CreateRequest1 request) {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task CreateAsync(CrmIntegration.Core.ServiceReferenceNaumen.createRequest CreateRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.CreateRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.CreateRequest1();
            inValue.CreateRequest = CreateRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void CrmIntegration.Core.ServiceReferenceNaumen.Service.Get(CrmIntegration.Core.ServiceReferenceNaumen.GetRequest1 request) {
            base.Channel.Get(request);
        }
        
        public void Get(CrmIntegration.Core.ServiceReferenceNaumen.getRequest GetRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.GetRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.GetRequest1();
            inValue.GetRequest = GetRequest;
            ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).Get(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task CrmIntegration.Core.ServiceReferenceNaumen.Service.GetAsync(CrmIntegration.Core.ServiceReferenceNaumen.GetRequest1 request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task GetAsync(CrmIntegration.Core.ServiceReferenceNaumen.getRequest GetRequest) {
            CrmIntegration.Core.ServiceReferenceNaumen.GetRequest1 inValue = new CrmIntegration.Core.ServiceReferenceNaumen.GetRequest1();
            inValue.GetRequest = GetRequest;
            return ((CrmIntegration.Core.ServiceReferenceNaumen.Service)(this)).GetAsync(inValue);
        }
    }
}
